{
	"_Type": "Action.Type.ClosePage",
	"ActionResult": {
		"_Name": "CloseModalPage_Complete"
	},
	"OnFailure": "/DemoSampleApp/Actions/UpdateCustomerEntityFailureMessage.action",
	"OnSuccess": "/DemoSampleApp/Actions/CloseModalPage_Complete.action",
	"DismissModal": "Action.Type.ClosePage.Completed",
	"CancelPendingActions": false
}